// Predefined list of officer email addresses
export const OFFICER_EMAILS: Set<string> = new Set([
  // Add officer emails here
  "lobatonl@uci.edu",
  "dkaloust@uci.edu",
  "nalara1@uci.edu",
  "sokraksh@uci.edu",
  "gdodge@uci.edu",
  "ccweinbe@uci.edu",
  "mkuhi@uci.edu",
  "ostdieke@uci.edu",
  "henkkab@uci.edu",
  "wharring@uci.edu",
  "kaylamk2@uci.edu",
  "sbarsan@uci.edu",
  "lokeshs1@uci.edu",
  "woodburp@uci.edu",
]);

export function isOfficerEmail(email: string): boolean {
  return OFFICER_EMAILS.has(email.toLowerCase());
}

export const MEMBER_EMAILS: Set<string> = new Set([
  // Add member emails here
  "gdodge@uci.edu",
  "nhdo2@uci.edu",
  "pnkim@uci.edu",
  "joeyeb@uci.edu",
  "tlliang1@uci.edu",
  "osheldondomains@gmail.com",
  "kaylamk2@uci.edu",
  "sokraksh@uci.edu",
  "seoyoj1@uci.edu",
  "jyoungb1@uci.edu",
  "nalara1@uci.edu",
  "dkaloust@uci.edu",
  "mtkhaing@uci.edu",
  "akalkows@uci.edu",
  "hobbsa1@uci.edu",
  "jlabacze@uci.edu",
  "caror@uci.edu",
  "stsulaia@uci.edu",
  "ccweinbe@uci.edu",
  "amkheidz@uci.edu",
  "edwarmc2@uci.edu",
  "mkuhi@uci.edu",
  "scampilo@uci.edu",
  "mbulloch@uci.edu",
  "minxuanx@uci.edu",
  "ingramaj@uci.edu",
  "wesleyi@uci.edu",
  "klaltoo@uci.edu",
  "henkkab@uci.edu",
  "rachelz9@uci.edu",
  "chowdhuw@uci.edu",
  "apjosep1@uci.edu",
  "tpomared@uci.edu",
  "errodri3@uci.edu",
  "zeniadag@uci.edu",
  "lilinh3@uci.edu",
  "yaqiw11@uci.edu",
  "natheneg@uci.edu",
  "hje@uci.edu",
  "dayoul3@uci.edu",
  "gwithrow@uci.edu",
  "jrcrawfo@uci.edu",
  "nfcastel@uci.edu",
  "haleyn5@uci.edu",
  "llyche@uci.edu",
  "tmckenny@uci.edu",
  "woodburp@uci.edu",
  "matthl30@uci.edu",
  "brendac9@uci.edu",
  "mkommire@uci.edu",
  "cynthtc1@uci.edu",
  "ambec14@uci.edu",
  "phoeby2@uci.edu",
  "mfrieder@uci.edu",
  "yangfy@uci.edu",
  "balderak@uci.edu",
  "sophianinan5@gmail.com",
  "ostdieke@uci.edu",
  "radanie1@uci.edu",
  "cmoon2@uci.edu",
  "anastajl@uci.edu",
  "pragyans@uci.edu",
  "nicholnb@uci.edu",
  "lobatonl@uci.edu",
  "annaho110304@gmail.com",
  "sbarsan@uci.edu",
  "wharring@uci.edu",
]);

export function isMemberEmail(email: string): boolean {
  return MEMBER_EMAILS.has(email.toLowerCase());
}
